export {
  useFetchData,
  isNotFoundError,
  type IUseFetchData,
  type IFetchDataOptions,
  type IMessageError,
  type TResponse,
  type TResponseError,
  type TUseFetchDataResult,
  useApiMutation,
  type IApiMutationOptions,
  useInfiniteFetchData,
  type IUseInfiniteFetchData,
  type IInfiniteFetchDataOptions,
  useCacheUpdater,
  createCrudHooks,
  type CrudHooksConfig,
  type CrudService,
  clinicListOptions,
  LIVE_LIST_OPTIONS,
  DASHBOARD_OPTIONS,
  BILLING_OPTIONS,
  toQueryOptions,
  INVALIDATE,
} from '@/core/api/query';
