export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SCHEDULE: '/schedule',
  SCHEDULE_NEW: '/schedule/new',
  SCHEDULE_EDIT: (id: string) => `/schedule/${id}/edit`,
  PATIENTS: '/patients',
  PATIENT_NEW: '/patients/new',
  PATIENT_DETAIL: (id: string) => `/patients/${id}`,
  PRACTITIONERS: '/practitioners',
  PRACTITIONERS_NEW: '/practitioners/new',
  PRACTITIONER_DETAIL: (id: string) => `/practitioners/${id}`,
  PRACTITIONERS_EDIT: (id: string) => `/practitioners/${id}/edit`,
  REPORTS: '/reports',
  SETTINGS: '/settings',
  SETTINGS_DEPARTMENTS: '/settings/departments',
  SETTINGS_ROOMS: '/settings/rooms',
  SETTINGS_SERVICES: '/settings/services',
  SETTINGS_PAYMENT_METHODS: '/settings/payment-methods',
  SETTINGS_PACKAGES: '/settings/packages',
  SETTINGS_DISCOUNT_CODES: '/settings/discount-codes',
  SETTINGS_CLINIC: '/settings/clinic',
} as const;
